[versions]
#kotlin = "1.8.0"
#gradle = "7.4.2"
#ktLint = "10.3.0"
#detekt = "1.19.0"
#gradle-version-update = "0.42.0"
#google_services = "4.3.13"
#firebase-appDistribution = "3.0.3"
#firebase-crashlytics = "2.9.1"
#firebase-performance = "1.4.1"
#
kotlinxCoroutines = "1.6.4"
koinCore = "3.3.3"
koinAndroid = "3.3.3"
koinCompose = "3.4.2"
kotlinxSerializationJson = "1.5.0"
kotlinxDateTime = "0.3.2"
napier = "2.4.0"
ktor = "2.2.3"
#sqlDelight = "1.5.5"
multiplatformSettings = "0.8.1"

#kmpNativeCoroutines = "0.12.1-new-mm"
#buildKonfig = "0.13.3"
#kover = "0.6.1"
#
mockk = "1.12.3"
kotlinxTestResources = "0.2.2"
#
#compose-desktop = "1.3.0"
#kamel = "0.2.2"
#
#android-core = "1.7.0"
#material = "1.6.0"
#appCompat = "1.4.1"
#constraintLayout = "2.1.4"
#compose = "1.2.0-alpha08"
#compose-Material3 = "1.0.0-alpha13"
#compose-activity = "1.4.0"
#compose-constraint = "1.0.0-rc01"
#accompanist = "0.25.1"
#navigation = "2.4.0-alpha02"
#lifecycle = "2.3.1"
#coil = "1.4.0"
#palette = "28.0.0"
#paging = "3.0.0"
#coroutines = "1.5.2"
#firebase-bom = "30.3.1"
#rating-bar = "1.1.1"
#leakCanary = "2.9.1"
#paging-compose = "1.0.0-alpha14"
#oneBoneToolbar = "2.3.4"
#
#jUnit = "4.13.2"
#truth = "1.1.3"
#coroutinesTest = "1.5.0"
#robolectric = "4.5.1"
#jUnitKtx = "1.1.2"
#espresso = "3.3.0"
#testCore = "1.3.0"
#archTestCore = "2.1.0"
#testRules = "1.3.0"
#testRunner = "1.3.0"

[plugins]

[libraries]
kotlinX-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinCore" }

kotlinX-serializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationJson" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }

#sqlDelight = { module = "com.squareup.sqldelight:runtime", version.ref = "sqlDelight" }
#sqlDelight-coroutine = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
#sqlDelight-android = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqlDelight" }
#sqlDelight-native = { module = "com.squareup.sqldelight:native-driver", version.ref = "sqlDelight" }
#sqlDelight-JVM = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqlDelight" }

napier = { module = "io.github.aakira:napier", version.ref = "napier" }

kotlinX-dateTime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDateTime" }

multiplatformSettings-noArg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatformSettings" }
multiplatformSettings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "multiplatformSettings" }
multiplatformSettings-test = { module = "com.russhwolf:multiplatform-settings-test", version.ref = "multiplatformSettings" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

kotlinX-testResources = { module = "com.goncalossilva:resources", version.ref = "kotlinxTestResources" }

kotlinX-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }